### ISSUE TITLE
https://devdocs.io & https://getmimo.com/

### ISSUE THREAD

**Issue by diegoarcega** [MarcosRenato266/Grow-Roadmaps#11]
A ideia inicial do grow roadmaps eu acho interessante, porem, nao vi muita diferenca para o [devdocs](https://devdocs.io), onde vc pode ter acesso a documentacao de tudo praticamente. 

Em termos de maior entrega de valor, acredito que se o modelo deste projeto fosse mais fundo no conceito de  "gamification", mais na linha do [mimo](https://getmimo.com/) acredito que adicionaria mais ao aprendizado. Esse mimo eh bem interessante, como se fosse um duolingo para pogramacao. O que acho interessante tb nele eh que sao licoes bem rapidas, nao fica aqueles textos massivos pra ler.

**Comment by MarcosRenato266** [comment]
Os dois projetos são bem bacanas! Mas não acho que as ideias sejam similares, posso ser um pouco suspeito para falar mas a ideia não é bem essa. Pensa da seguinte forma: quantas vezes seus amigos não pediram para você oque estudar para ser programador, ou você mesmo guardou um link de uma pessoa explicando muito bem um determinada tecnologia... A ideia é termos um lugar para compartilhar esses "links" sagrados e organizados por ordem cronológica de aprendizado. Esse projeto pode ser não só alem de gamefication e um local de estudos mas pode ser tambem um feed de atualizações em tecnologias, um network de compartilhamento de conteúdo para novos criadores onde por meio da qualidade individual do video deles eles vão ganhar mais upvotes e consequentemente mais "relevancia" do que em suas devidas plataformas(youtube, facebook e etc). Atualmente toda plataforma de conteúdo baseia a relevancia em numero de views e não em qualidade, a ideia aqui é essa. Dar voz a conteúdo de execelente qualidade, mesmo que de baixa visibilidade porque afinal, os melhores conteúdos são assim... pouco populares e de grande qualidade :)

**Comment by diegoarcega** [comment]
Show legal Marcos...acredito que agora entendi um pouco mais a ideia do projeto. Vou fechar a issue.
