### ISSUE TITLE
Branch default 

### ISSUE THREAD

**Issue by cloudson** [MarcosRenato266/Grow-Roadmaps#19]
Quando abri uma pull request ele apontou pra master, mas na verdade a branch com a versão mais atual é a develop. Então sugiro algumas opções de mudança: 

1) Ou mudamos o branch default para develop, para não causar confusão para quem baixar o projeto e fazer pull request. 
2) Ou trabalhamos apenas com uma branch (mandando tudo pra master e deletando a develop), acho que isso faz sentido porque antes de um release mais formal, não tem muito porque manter duas branches, git-flow vai só burocratizar as coisas, na minha opinião.

**Comment by rafaelalmeidatk** [comment]
Concordo com `develop` sendo a branch padrão. Prefiro não deletar ela e usar a master porque eventualmente teriamos que recriar ela de qualquer forma, é só ignorar a master por enquanto.

**Comment by MarcosRenato266** [comment]
Prontinho!
