### ISSUE TITLE
Estado de Conteúdo Vazio

### ISSUE THREAD

**Issue by MarcosRenato266** [MarcosRenato266/Grow-Roadmaps#9]
Quando nenhum modulo foi selecionado aparecer instruções solicitando que selecione um módulo.

**Comment by diegoarcega** [comment]
Tem design para esta tarefa? talvez fosse bom adicionar uma label (design-required) algo assim, pra saber se existe, ou ter o link para o design desta atividade.

**Comment by MarcosRenato266** [comment]
@diegoarcega ainda nao fiz, mas eu estava pensando em fazer um "skeleton". Se nao soubee oque é, é tipo aqueles shapes no formato do conteudo que sao exibidos antes do conteúdo ser carregado como no facebook por ex.

**Comment by LucasLeandroBR** [comment]
E como se fosse somente o wireframe do componente

**Comment by diegoarcega** [comment]
Tipo isso https://github.com/buildo/react-placeholder ?

**Comment by MarcosRenato266** [comment]
isso, se for usar um já pronto usa o do antd [https://ant.design/components/skeleton/](url) que já está instalado. Mas acho que pra ficar top precisaria fazer na munheca mesmo para ficar literalmente um skeleton desse componente em especifico. Esses prontos deixam você personalizar somente o básico.

**Comment by MarcosRenato266** [comment]
Resolvido
